# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Index < Formula
  desc "Cli"
  homepage "https://github.com/noetic-sys/index"
  url "https://github.com/noetic-sys/index/archive/refs/tags/v0.1.3.tar.gz"
  sha256 "6f05815e330b51991f1dae1c0bb1f2e75fdacdafd0a7331ebc8d70fc20892e8e"
  license "AGPL-3.0"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install Dir["idx-*"].first => "idx"
  end

  test do
    system "#{bin}/idx", "--version"
  end
end
