# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Index < Formula
  desc "Local semantic search for your dependencies mcp server for claude code"
  homepage "https://github.com/noetic-sys/index"
  url "https://github.com/noetic-sys/index/archive/refs/tags/v0.1.7.tar.gz"
  sha256 "7dd6c01917e91b508484027bcd3633bfe4544f316a42e18b294697b890e59b36"
  license "AGPL-3.0"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install Dir["idx-*"].first => "idx"
  end

  test do
    system "#{bin}/idx", "--version"
  end
end
