# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Index < Formula
  desc "Local semantic search for your dependencies mcp server for claude code"
  homepage "https://github.com/noetic-sys/index"
  url "https://github.com/noetic-sys/index/archive/refs/tags/v0.1.5.tar.gz"
  sha256 "fc2268b560434390de82ab3e43a408c6e18671779cf6c645a061c928c9180d4a"
  license "AGPL-3.0"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install Dir["idx-*"].first => "idx"
  end

  test do
    system "#{bin}/idx", "--version"
  end
end
