# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Index < Formula
  desc "Local semantic search for your dependencies mcp server for claude code"
  homepage "https://github.com/noetic-sys/index"
  url "https://github.com/noetic-sys/index/archive/refs/tags/v0.1.4.tar.gz"
  sha256 "9a8df07d9f48dca3accb0c1e7ff9d8cc68f2e34634bc9d6575da24b86346b7fc"
  license "AGPL-3.0"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install Dir["idx-*"].first => "idx"
  end

  test do
    system "#{bin}/idx", "--version"
  end
end
